### ISSUE TITLE
Wrong number of args for safeHTML

### ISSUE THREAD

**Issue by mzdravkov** [esell/rocktopus#3]
I just installed this theme on a brand new website and got the following:

`ERROR: 2016/02/10 02:32:57 template.go:119: template: theme/partials/header.html:20:81: executing "theme/partials/header.html" at <safeHTML>: wrong number of args for safeHTML: want 1 got 0 in theme/partials/header.html`

**Comment by mzdravkov** [comment]
Well, this is a pretty obvious mistake: I had to copy the sample_cofig as config in the root dir.

**Comment by esell** [comment]
Yeah, the theme will look a little strange without the `blogHeader` param but it should be able to still build. I just pushed commit https://github.com/esell/rocktopus/commit/4fa14144c7018691587f3ebc3099e1dae2937c7e that will solve the error you were getting. Thanks for the heads up.
